# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2213296d66492bcbe9b437a9a54699fa90ad699576e59809167c026448c0f8df622298adb8ac1516df8535c3957367b7c6f38d368a38e185a06acbc2c47b0353

test:
  secret_key_base: 4ac2949b0c92f2fb291512052abb662544b1caca836c68481e9ead508f5ab4a0287078509b5ae0b5c968d9aa76db06c0410d199d895481769b8557db971d5d64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
